[package]
name = "atomic-ext"
version = "0.3.1"
edition = "2021"
license = "MIT"
homepage = "https://github.com/huachaohuang/atomic-ext"
description = "Extensions for atomic operations."

[dependencies]
